import { BASE_PATTERN_DEFINITIONS } from "./patterns.js";

export const DEFAULT_COLOR_PATTERN = "classic";

function hexToRgb(hexColor) {
  const hex = hexColor.replace("#", "");
  return {
    r: Number.parseInt(hex.slice(0, 2), 16),
    g: Number.parseInt(hex.slice(2, 4), 16),
    b: Number.parseInt(hex.slice(4, 6), 16)
  };
}

function toRgba(hexColor, alpha) {
  const { r, g, b } = hexToRgb(hexColor);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function mixHex(firstColor, secondColor, ratio) {
  const first = hexToRgb(firstColor);
  const second = hexToRgb(secondColor);
  const r = Math.round(first.r + (second.r - first.r) * ratio);
  const g = Math.round(first.g + (second.g - first.g) * ratio);
  const b = Math.round(first.b + (second.b - first.b) * ratio);
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

function createThemeColors(mainColor, textColor, textBackgroundColor, overrides = {}) {
  const secondaryColor = overrides.secondaryColor ?? mixHex(mainColor, textColor, 0.22);
  return {
    mainColor,
    textColor,
    textBackgroundColor,
    secondaryColor,
    surfaceColor: overrides.surfaceColor ?? textBackgroundColor,
    mutedColor: overrides.mutedColor ?? toRgba(textColor, 0.74),
    borderColor: overrides.borderColor ?? toRgba(textColor, 0.28),
    softColor: overrides.softColor ?? toRgba(textBackgroundColor, 0.86),
    inputBgColor: overrides.inputBgColor ?? toRgba(textBackgroundColor, 0.74),
    inputTextColor: overrides.inputTextColor ?? textColor,
    successColor: overrides.successColor ?? mixHex(mainColor, "#22c55e", 0.58),
    dangerColor: overrides.dangerColor ?? mixHex(mainColor, "#ef4444", 0.62)
  };
}

function mapPatternDefinition(definition) {
  return {
    id: definition.id,
    label: definition.label,
    markdownLabel: definition.markdownLabel,
    colors: createThemeColors(
      definition.mainColor,
      definition.textColor,
      definition.textBackgroundColor,
      definition.overrides ?? {}
    )
  };
}

export const COLOR_PATTERNS = BASE_PATTERN_DEFINITIONS.map(mapPatternDefinition);

export const COLOR_PATTERN_OPTIONS = COLOR_PATTERNS.map((pattern) => ({
  id: pattern.id,
  label: pattern.label,
  markdownLabel: pattern.markdownLabel
}));

export function isValidColorPattern(patternId) {
  return COLOR_PATTERNS.some((pattern) => pattern.id === patternId);
}

export function getPatternById(patternId, fallbackId = DEFAULT_COLOR_PATTERN) {
  const found = COLOR_PATTERNS.find((pattern) => pattern.id === patternId);
  if (found) {
    return found;
  }
  return COLOR_PATTERNS.find((pattern) => pattern.id === fallbackId) ?? COLOR_PATTERNS[0];
}

export function getThemeVariables(patternId, fallbackId = DEFAULT_COLOR_PATTERN) {
  const pattern = getPatternById(patternId, fallbackId);
  const { colors } = pattern;

  return {
    "--theme-primary": colors.mainColor,
    "--theme-secondary": colors.secondaryColor,
    "--theme-surface": colors.surfaceColor,
    "--theme-text": colors.textColor,
    "--theme-muted": colors.mutedColor,
    "--theme-border": colors.borderColor,
    "--theme-soft": colors.softColor,
    "--theme-textbackground": colors.textBackgroundColor,
    "--theme-input-bg": colors.inputBgColor,
    "--theme-input-text": colors.inputTextColor,
    "--theme-success": colors.successColor,
    "--theme-danger": colors.dangerColor
  };
}

export function getMarkdownThemeVariables(patternId, fallbackId = DEFAULT_COLOR_PATTERN) {
  const pattern = getPatternById(patternId, fallbackId);
  const { colors } = pattern;
  return {
    "--main-color": colors.mainColor,
    "--text-color": colors.textColor,
    "--textbackground-color": colors.textBackgroundColor
  };
}

export function buildThemeClassCss(rootSelector = ".Main", fallbackId = DEFAULT_COLOR_PATTERN) {
  const lines = ["/* Generated by @hasm/color-patterns */"];

  const fallbackVariables = getMarkdownThemeVariables(fallbackId, DEFAULT_COLOR_PATTERN);
  lines.push(":root {");
  Object.entries(fallbackVariables).forEach(([name, value]) => {
    lines.push(`  ${name}: ${value};`);
  });
  lines.push("}");
  lines.push("");

  COLOR_PATTERNS.forEach((pattern) => {
    lines.push(`${rootSelector}.theme-${pattern.id} {`);
    const cssVars = getMarkdownThemeVariables(pattern.id, fallbackId);
    Object.entries(cssVars).forEach(([name, value]) => {
      lines.push(`  ${name}: ${value};`);
    });
    lines.push("}");
    lines.push("");
  });

  return lines.join("\n").trim() + "\n";
}
